baseURL = 'https://lightsandshapes.com/'
languageCode = 'en-us'
title = 'Lights and Shapes'
theme = 'paper'

disqusShortname = 'lightsandshapes'

pagination.pagerSize = 8 

custom_css = ["css/custom.css"]


[params]
  # color style
  color = 'gray'                           # linen, wheat, gray, light

  # header social icons
  bluesky = 'papertigers.net'                      # bsky.app/profile/YOUR_BLUESKY_ID
  github = 'papertigers'                           # github.com/YOUR_GITHUB_ID
  instagram = 'chromaticadventure'                 # instagram.com/YOUR_INSTAGRAM_ID
  mastodon = 'https://hachyderm.io/@papertigers'   # e.g. 'https://mastodon.instance/@xxx'
  #rss = true                                      # show rss icon

  # home page profile
  avatar = 'mike@mikezeller.net'                 # gravatar email or image url
  name = 'Mike Zeller'
  bio = 'Software Engineer ðŸ’»'


  # misc
  #disableHLJS = true                        # disable highlight.js
  monoDarkIcon = true                       # show monochrome dark mode icon
